### ISSUE TITLE
Electronite for NPM

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6661]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
It appears that we will need to create a fork of electron-packager and edit this file https://github.com/electron/electron-packager/blob/master/src/download.js to re-configure `downloadArtifact`.

We should still be able to use `@electron/get` since it can be reconfigured to use a mirror. We would simply point it to our electronite. See https://www.npmjs.com/package/@electron/get

All of the above is necessary to build an electronite application.

**Comment by da1nerd** [comment]
Now I just need to figure out how we can easily use electronite without having to install electron. I'd like to be able to simply install `electronite` and `electronite-packager`, however I do not want to re-build the entire infrastructure for caching, downloading, js apis, etc.

For now, an easily solution might be to make an `electronite` package that imports `electron` internally and exposes it's js APIs publicly. Then this package can download the proper version of the electronite binary, though electron will end up being downloaded as well.

**Comment by neutrinog** [comment]
For now, an easily solution might be to make an `electronite` package that imports `electron` internally and exposes it's js APIs publicly. Then this package can download the proper version of the electronite binary.

**Comment by da1nerd** [comment]
Here's my first attempt at an `electronite` package. So far so good.
![Screenshot from 2020-02-05 16-36-02](https://user-images.githubusercontent.com/166412/73829850-3a31d680-4836-11ea-8e64-5c7605e3c947.png)

**Comment by da1nerd** [comment]
not able to get the js api working yet though. not sure what's wrong.

**Comment by da1nerd** [comment]
I've published a new npm package https://www.npmjs.com/package/electronite.
Only one package left to build!

**Comment by da1nerd** [comment]
Made some progress on a packager package. Repo at https://github.com/unfoldingWord-box3/electronite-packager.
It's correctly using electronite, but I'm receiving some errors after building (can't find electronite). It seems that for some reason the electronite package is not being included in the build even though it's in the dependencies and not devDependencies.

**Comment by da1nerd** [comment]
I think the problem is that my demo application does not run the main.js through webpack, so it's not resolving the electronite import to the node module.

**Comment by da1nerd** [comment]
for posterity here's my error.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electronite'
Require stack:
- /home/joel/git/neutrinog/electronite-test/dist/react-app-electron-template-linux-x64/resources/app/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/joel/git/neutrinog/electronite-test/dist/react-app-electron-template-linux-x64/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/joel/git/neutrinog/electronite-test/dist/react-app-electron-template-linux-x64/resources/app/main.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)

```

Since everything under `./public` is copied into `./build` and not ran through webpack, it's missing the npm dependencies.

**Comment by da1nerd** [comment]
I've managed get main.js to compile with webpack so that electronite get's bundled. 

Here's basically what the file structure looks like. `src` and `electron` get compiled independently before we finally compile the full application.
![image](https://user-images.githubusercontent.com/166412/77154153-bbcf8200-6acd-11ea-8ccf-75e444ae726b.png)

However, I don't like having the extra webpack.config.js file. I'd rather keep everything running through the craco scripts so we can have a uniform and update-able development experience. We might be able to accomplish this by creating a `craco.main.config.js` and `craco.render.config.js` and manually pointing to each of those. Or we could take in a parameter and provide the two configurations in the same file.

**Comment by da1nerd** [comment]
I've finished creating the electronite packages. https://www.npmjs.com/package/electronite and https://www.npmjs.com/package/electronite-packager.

The complications with properly compiling the electron main.js file have been resolved and placed into this template repo https://github.com/neutrinog/react-app-electron-template. That will also help with problems in #6726

**Comment by da1nerd** [comment]
I think this should be closed now. We are already on to 7.2.1

**Comment by BincyJ** [comment]
@PhotoNomad0 please confirm if we can close this issue. Thanks.

**Comment by mannycolon** [comment]
I can attest this works, will close the issue
